// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJmpTICVW6jP_4vXL18q5oaakGwn07D4',
    appId: '1:1096418365943:web:e52f04a7ae55e2590edef2',
    messagingSenderId: '1096418365943',
    projectId: 'reddoc-authentication',
    authDomain: 'reddoc-authentication.firebaseapp.com',
    storageBucket: 'reddoc-authentication.firebasestorage.app',
    measurementId: 'G-Y32EDE6Q2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-FzGR0vNr7aL2U1ZqNyP1j_UE_nrUVU',
    appId: '1:1096418365943:android:80f79adfa2d415a60edef2',
    messagingSenderId: '1096418365943',
    projectId: 'reddoc-authentication',
    storageBucket: 'reddoc-authentication.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUHaAtIED-cWfGBTTDFUoO67MUXU1QhU',
    appId: '1:1096418365943:ios:39c4a665444025230edef2',
    messagingSenderId: '1096418365943',
    projectId: 'reddoc-authentication',
    storageBucket: 'reddoc-authentication.firebasestorage.app',
    iosBundleId: 'com.example.redDoc',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUHaAtIED-cWfGBTTDFUoO67MUXU1QhU',
    appId: '1:1096418365943:ios:39c4a665444025230edef2',
    messagingSenderId: '1096418365943',
    projectId: 'reddoc-authentication',
    storageBucket: 'reddoc-authentication.firebasestorage.app',
    iosBundleId: 'com.example.redDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJmpTICVW6jP_4vXL18q5oaakGwn07D4',
    appId: '1:1096418365943:web:5413ac650607084d0edef2',
    messagingSenderId: '1096418365943',
    projectId: 'reddoc-authentication',
    authDomain: 'reddoc-authentication.firebaseapp.com',
    storageBucket: 'reddoc-authentication.firebasestorage.app',
    measurementId: 'G-TVBME4RTR6',
  );
}
